# Generated by Django 5.0.2 on 2024-09-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=200)),
                ('todo_desc', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('todo_status', models.BooleanField(default=False)),
            ],
        ),
    ]
