# Generated by Django 5.0.2 on 2024-09-29 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 19, 38, 36, 560259)),
        ),
    ]
