# Generated by Django 5.0.2 on 2024-09-29 18:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time_created',
            field=models.DateTimeField(default=api.models.one_hour_ago),
        ),
    ]
